<a href="https://colab.research.google.com/github/prinsha13/6CS012_Worksheet/blob/main/6CS012_Worksheet_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1. Exercise on Python**

#Function
##Task-01

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [56]:
def length(value, initial_unit, converted_unit):
    if initial_unit == 'm' and converted_unit == 'ft':
        return value * 3.28084
    elif initial_unit == 'ft' and converted_unit == 'm':
        return value / 3.28084
    else:
        return "Invalid conversion"

def weight(value, initial_unit, converted_unit):
    if initial_unit == 'kg' and converted_unit == 'lbs':
        return value * 2.20462
    elif initial_unit == 'lbs' and converted_unit == 'kg':
        return value / 2.20462
    else:
        return "Invalid conversion"

def volume(value, initial_unit, converted_unit):
    if initial_unit == 'L' and converted_unit == 'gal':
        return value * 0.264172
    elif initial_unit == 'gal' and converted_unit == 'L':
        return value / 0.264172
    else:
        return "Invalid conversion"

def main():
    print("Choose a type of conversion:")
    print("\n1. Length \n2. Weight \n3. Volume")

    try:
        choice = int(input("Enter your choice (1/2/3): "))

        if choice == 1:
            value = float(input("Enter the value to convert: "))
            initial_unit = input("Enter the initial unit (m/ft): ").strip().lower()
            converted_unit = input("Enter the convert unit (m/ft): ").strip().lower()
            result = length(value, initial_unit, converted_unit)
            print(f"{value} {initial_unit} is equal to {result} {converted_unit}")

        elif choice == 2:
            value = float(input("Enter the value to convert: "))
            initial_unit = input("Enter the initial unit (kg/lbs): ").strip().lower()
            converted_unit = input("Enter the convert unit (kg/lbs): ").strip().lower()
            result = weight(value, initial_unit, converted_unit)
            print(f"{value} {initial_unit} is equal to {result} {converted_unit}")

        elif choice == 3:
            value = float(input("Enter the value to convert: "))
            initial_unit = input("Enter the initial unit (L/gal): ").strip()
            converted_unit = input("Enter the convert unit (L/gal): ").strip()
            result = volume(value, initial_unit, converted_unit)
            print(f"{value} {initial_unit} is equal to {result} {converted_unit}")

        else:
            print("Invalid choice. Please select 1, 2, or 3.")

    except ValueError:
        print("Invalid input. Please enter a valid number.")

main()


Choose a type of conversion:

1. Length 
2. Weight 
3. Volume
Enter your choice (1/2/3): 2
Enter the value to convert: 53
Enter the initial unit (kg/lbs): kg
Enter the convert unit (kg/lbs): lbs
53.0 kg is equal to 116.84485999999998 lbs


##Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [79]:
def calculate_sum(numbers):
  return sum(numbers)

def average(numbers):
  if len(numbers) == 0:
    return "Invalid calculations"
  return sum(numbers) / len(numbers)

def maximum(numbers):
  if len(numbers) == 0:
    return "Invalid calculation"
  return max(numbers)

def minimum(numbers):
  if len(numbers) == 0:
    return "Invalid calculation"
  return min(numbers)

def main():
  print("Choose an operation:")
  print("\n1. Sum \n2. Average \n3. Maximum \n4. Minimum")

  try:
    choice = int(input("Enter your choice (1/2/3/4): "))

    user_input = input("Enter the list of numbers(sperated by spaces):")
    numbers = list(map(float, user_input.split()))

    if choice == 1:
      result =calculate_sum(numbers)
      print("The sum of the numbers is: ", result)
    elif choice == 2:
      result = average(numbers)
      print("The average of the numbers is: ", result)
    elif choice == 3:
      result = maximum(numbers)
      print("The maximum of the numbers is: ", result)
    elif choice == 4:
      result = minimum(numbers)
      print("The minimum of the numbers is: ", result)
    else:
      return "Invalid choice."

  except ValueError:
        print("Invalid input. Please enter a valid number.")

if __name__ == "__main__":
    main()

Choose an operation:

1. Sum 
2. Average 
3. Maximum 
4. Minimum
Enter your choice (1/2/3/4): 1
Enter the list of numbers(sperated by spaces):1 2 3 4 5
The sum of the numbers is:  15.0


##Exercise on List Manipulation:
**1. Extract Every Other Element:**

Write a Python function that extracts every other element from a list, starting from the first element.

In [58]:
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


**2. Slice a Sublist:**

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [59]:
def get_sublist(lst, start, end):
    return lst[start:end + 1]  # Include the end index by adding 1

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))


[3, 4, 5]


**3. Reverse a List Using Slicing:**

Write a Python function that reverses a list using slicing.

In [60]:
def reverse_list(lst):
    return lst[::-1]  # Slice with a step of -1 to reverse the list

print(reverse_list([1, 2, 3, 4, 5]))


[5, 4, 3, 2, 1]


**4. Remove Specific Element from a Nested List:**

Write a Python function that removes all occurrences of a specific element from a nested list.

In [61]:
def remove_first_last(lst):
    return lst[1:-1]  # Exclude the first and last elements

print(remove_first_last([1, 2, 3, 4, 5]))


[2, 3, 4]


**5. Find the Maximum Element in a Nested List:**

Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [62]:
def find_max(lst):
    max_value = float('-inf')  #Initialize with the smallest possible value

    def find_max_val(sublist):
        nonlocal max_value
        for item in sublist:
            if isinstance(item, list):
                find_max_val(item)  # Recursively check the nested lists
            else:
                max_value = max(max_value, item)  # Update the max value

    find_max_val(lst)
    return max_value

print(find_max([[1, 2], [3, [4, 5]], 6]))


6


**6. Count Occurrences of an Element in a Nested List:**

Write a Python function that counts how many times a specific element appears in a nested list.

In [63]:
def count_occurrences(lst, elem):
    count = 0
    for sublist in lst:
        count += sublist.count(elem)  # Count the occurrences in each sublist
    return count
lst = [[1, 2], [2, 3], [2, 4]]
print(count_occurrences(lst, 2))


3


**7. Flatten a List of Lists of Lists:**

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [64]:
def deep_flatten(lst):
  flat_list = []
  for item in lst:
    if isinstance(item, list):  #If the item is a list, call deep_flatten
      flat_list.extend(deep_flatten(item))
    else:   #If it's not a list, add it to the result
      flat_list.append(item)
  return flat_list

print(deep_flatten([[[1,2], [3,4]], [[5,6], [7, 8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**

Write a Python function that calculates the average of all elements in a nested list.

In [65]:
def average_nested(lst):
  total = 0
  count = 0

  for sublist in lst:
    total += sum(sublist) #add sum fo elements in sublist
    count += len(sublist) #Count the number of element in the sublist
  return total/count #Calculate the average

print(average_nested([[1,2,3], [4,5,6]]))

3.5


#**2. Exercise on Numpy**
##Basic Vector and Matrix Operation with Numpy.




**Problem-1: Array Creation**

In [66]:
import numpy as np

In [67]:
# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty Array:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All-Ones Array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
new_array = np.full((3, 3), 7)
print("\n3. Full Array with fill value 7:\n", new_array)

# 4. Return a new array of zeros with the same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])
new_zeros_array = np.zeros_like(given_array)
print("\n4. Zeros Like Array:\n", new_zeros_array)

# 5. Return a new array of ones with the same shape and type as a given array
new_ones_array = np.ones_like(given_array)
print("\n5. Ones Like Array:\n", new_ones_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted NumPy Array:\n", numpy_array)


1. Empty Array:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. All-Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full Array with fill value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Like Array:
 [[0 0 0]
 [0 0 0]]

5. Ones Like Array:
 [[1 1 1]
 [1 1 1]]

6. Converted NumPy Array:
 [1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

In [68]:
# 1. Create an array with values ranging from 10 to 49.
array_range = np.arange(10, 50)
print("1. Array with values ranging from 10 to 49:\n", array_range)

# 2. Create a 3X3 matrix with values ranging from 0 to 8.
matrix = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix with values ranging from 0 to 8:\n", matrix)

# 3. Create a 3X3 identity matrix.
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array.
random_array = np.random.rand(30)
mean_value = np.mean(random_array)
print("\n4. Random Array:\n", random_array)
print("\nMean of the array:", mean_value)

# 5. Create a 10X10 array with random values and find the minimum and maximum values.
random_matrix = np.random.rand(10, 10)
min_value = np.min(random_matrix)
max_value = np.max(random_matrix)
print("\n5. Random 10x10 Matrix:\n", random_matrix)
print("\nMinimum value:", min_value)
print("\nMaximum value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero array with replaced 5th element with 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed Array:", reversed_arr)

# 8. Create a 2d array with 1 on border and 0 inside.
arr_2d = np.ones((5, 5))
arr_2d[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", arr_2d)

# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerborad pattern:\n", checkerboard)

1. Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random Array:
 [0.95722732 0.29955111 0.93731481 0.65316227 0.967308   0.83673826
 0.54453989 0.29289466 0.8221682  0.93317269 0.66139221 0.63772497
 0.82650012 0.21880276 0.01376483 0.89509844 0.49555434 0.63100331
 0.50708384 0.11580151 0.21406159 0.33483786 0.1640733  0.15936396
 0.95473757 0.16010571 0.35058151 0.01776287 0.12168201 0.60692699]

Mean of the array: 0.5110312306401861

5. Random 10x10 Matrix:
 [[0.64239018 0.97125876 0.83643317 0.23093007 0.5900938  0.69241293
  0.79852584 0.84841043 0.0991927  0.84145026]
 [0.56383424 0.15768378 0.29418744 0.86900935 0.64344869 0.92340932
  0.04707554 0.45654528 0.63759623 0.58146529]
 [0.88441812 0.6249884  0.2686166  0.70835

**Problem - 3: Array Operations:**

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy.


In [69]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two array.
add_xy = x+y
print("1. Addition of x and y:\n", add_xy)

# 2. Subtract the two array.
sub_vw = v-w
print("\n2. Subtraction of v and w:\n", sub_vw)

# 3. Multiply the array with any integers of your choice.
multiply_x = x * 7
print("\n3. Multiplication of x with 7:\n", multiply_x)

# 4. Find the square of each element of the array.
square_y = np.square(y)
print("\n4. Square of y:\n", square_y)

# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v, w)  #Dot product of v and w
dot_xv = np.dot(x, v)  #Dot product of x and v
dot_xy = np.dot(x, y)  #Dot product of x and y

print("\n5. Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
concat_xy = np.concatenate((x, y), axis=0) #Row
concat_vw = np.vstack((v, w)) #Column
print("\n6. Concatenated x and y along row:\n", concat_xy)
print("Concatenated v and w along column:\n", concat_vw)

# 7. Concatenate x(and)v
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Attempting to concatenate along rows
except ValueError as e:
    print("\nError in concatenating x and v:", e)

1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of v and w:
 [-2 -2]

3. Multiplication of x with 7:
 [[ 7 14]
 [21 35]]

4. Square of y:
 [[25 36]
 [49 64]]

5. Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

6. Concatenated x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along column:
 [[ 9 10]
 [11 12]]

Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Explantion for the error in question 7:

The given matrix is 'x' is a 2D matrix and 'v' is a 1D array, when trying to concatenated these array both the arrays must have the same number of columns. However, in this case matrix 'v' is a 1D array whch does not have the same structure as the matrix 'x' hence resulting in an error.

**Problem - 4: Matrix Operations:**

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A^−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)^T = B^TA^T

In [70]:
# 1. Prove A.A^−1 = I.
A = np.array([[3, 4], [7,8]])
A_inverse = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inverse)
print("1. A.A^−1 = I:\n", identity_matrix)

1. A.A^−1 = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [71]:
# 2. Prove AB ̸= BA.
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB: \n", AB)
print("BA: \n", BA)

#Check if AB is equal to BA
print("\nIs AB = BA?", np.array_equal(AB, BA))

AB: 
 [[23 13]
 [51 29]]
BA: 
 [[36 44]
 [13 16]]

Is AB = BA? False


In [72]:
#3. Prove (AB)^T = B^TA^T
AB_T = np.transpose(AB) #Transpose of Ab

# Compute B^T * A^T
B_T = np.transpose(B)
A_T = np.transpose(A)
BT_AT = np.dot(B_T, A_T)

print("(AB)^T:\n", AB_T)
print("\nB^T * A^T:\n", BT_AT)

# Check if they are equal
print("\nIs (AB)^T = B^T * A^T?", np.array_equal(AB_T, BT_AT))


(AB)^T:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]

Is (AB)^T = B^T * A^T? True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

In [73]:
#Converting the equation into matirx and defining them as array
#Matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9]) #Matrix B
A_inv = np.linalg.inv(A) #Inverse of A
X = np.dot(A_inv, B) #Calculate X
print("x, y, z:", X)

x, y, z: [ 2.  1. -2.]


##Experiment: How Fast is Numpy?
1. Element-wise Addition

In [74]:
import time
size = 1000000

In [75]:
#Python lists
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Python List Addition Time:", end - start)

# Numpy Arrays
array1 = np.arange(size)
array2 = np.arange(size)

start = time.time()
array_addition = array1 + array2
end = time.time()
print("NumPy Array Addition Time:", end - start)

Python List Addition Time: 0.15102076530456543
NumPy Array Addition Time: 0.005702972412109375


2. Element-wise Multiplication


In [76]:
#Python Lists
start = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Python List Multiplication Time:", end - start)

#Numpy Arrays
start = time.time()
array_multiplication = array1 * array2
end = time.time()
print("NumPy Array Multiplication Time:", end - start)

Python List Multiplication Time: 0.18756651878356934
NumPy Array Multiplication Time: 0.005062580108642578


3. Dot Product

In [77]:
#Python Lists
start = time.time()
list_dot_product = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print("Python List Dot Product Time:", end - start)

#Numpy Arrays
start = time.time()
array_dot_product = np.dot(array1, array2)
end = time.time()
print("NumPy Array Dot Product Time:", end - start)

Python List Dot Product Time: 0.2202131748199463
NumPy Array Dot Product Time: 0.0022499561309814453


4. Matrix Multiplication

In [78]:
matrix_size= 1000
#Python Lists
matrix1 = [[i for i in range(matrix_size)] for j in range(matrix_size)]
matrix2 = [[i for i in range(matrix_size)] for j in range(matrix_size)]

start = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)] for i in range(matrix_size)]
end = time.time()
print("Python List Matrix Multiplication Time:", end - start)

#Numpy Arrays
np_matrix1 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)
np_matrix2 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)

start = time.time()
np_result_matrix = np.dot(np_matrix1, np_matrix2)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start)

Python List Matrix Multiplication Time: 192.9209017753601
NumPy Matrix Multiplication Time: 2.640974760055542
